language:
    java
    
dist: trusty

sudo:
    false

jdk:
    - oraclejdk8
    - oraclejdk9
    - oraclejdk10
    - oraclejdk11
    - openjdk7
    - openjdk8
    - openjdk9
    - openjdk10
    - openjdk11
    - openjdk-ea

matrix:
    allow_failures:
        - jdk: oraclejdk9
        - jdk: oraclejdk10
        - jdk: oraclejdk11
        - jdk: openjdk8
        - jdk: openjdk9
        - jdk: openjdk10
        - jdk: openjdk11
        - jdk: openjdk-ea
 
